name: mangos-docker
services:
  mangosd:
    image: mangos-server
    depends_on:
      - db
    restart: always
    ports:
      - "8085:8085"
    stdin_open: true
    tty: true
    volumes:
      - ./gamedata-extract/:/usr/local/gamedata
      - ./config/:/usr/local/etc/
    environment:
      - TZ=Pacific/Gambier
    command: ["/usr/local/bin/mangosd"]


  realmd:
    image: mangos-server
    depends_on:
      - db
    restart: always
    ports:
      - "3724:3724"
    volumes:
      - ./gamedata-extract/:/usr/local/gamedata
      - ./config/:/usr/local/etc/
    command: ["/usr/local/bin/realmd"]

  db:
    image: mysql:8.0.32
    hostname: mangosdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./database/:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mangosdb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root # Must match the `MARIADB_ROOT_PASSWORD` environment variable of the `database` service

networks:
  default:
    name: mangos_network 
    external: true

